### ISSUE TITLE
[PE-D] Recurring pop-up of reminders

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-4/tp#128]
![Screenshot 2022-04-01 at 2.31.38 PM.png](https://raw.githubusercontent.com/jaegarpoon/ped/main/files/716bd52c-ed9c-4e16-aea4-fa3d41a99683.png)

Unable to clear any reminders

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jaegarpoon/ped#3

**Comment by waffledood** [comment]
The Reminder Window is expected to continuously pop up every 1 minute until the user removes all reminders, will need to clarify this in the User Guide & Developer Guide
