### ISSUE TITLE
[PE-D] Cannot edit multiple properties.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-4/tp#129]
If the client has 1 property, I cannot add another one to the client through the edit command, even though the documentation states that property can accept multiple times.

![Screenshot 2022-04-01 at 2.32.03 PM.png](https://raw.githubusercontent.com/WJunHong/ped/main/files/7e550b3d-8a68-4382-95a4-35d1639cf05a.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: WJunHong/ped#5

**Comment by Ashuh** [comment]
Not a bug, user input for property field has the wrong format.

**Comment by howardwhw2** [comment]
Closed since it is not a bug.
