### ISSUE TITLE
[PE-D] Passing pr and pf fields multiple times?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-4/tp#145]
If clients have multiple property, how does user know which photo does each property the image belongs to other than naming. Is it possible to add more functionality to link image to specific property of user.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: lamwj98/ped#9

**Comment by howardwhw2** [comment]
Cannot be added due to the feature freeze
