### ISSUE TITLE
[PE-D] No example for format on editing preferences

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-4/tp#165]
UG does not give any examples regarding editing user's preferences

![image_2022-04-01_14-38-01.png](https://raw.githubusercontent.com/aidanaden/ped/main/files/08c2985e-4d49-430f-9494-1b7330f5f5d0.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: aidanaden/ped#5

**Comment by howardwhw2** [comment]
Example already given in use guide `edit 2 n/Betsy Crower p/1234567 pf/West, 1-room, $100000, $200000 Edits the name of the 2nd person to be Betsy Crower and updates the 2nd person to have a preference turning the 2nd person into a buyer.`
