### ISSUE TITLE
Incorrect String representation of a Person's Favourite status

### ISSUE THREAD

**Issue by waffledood** [AY2122S2-CS2103-W16-4/tp#181]
This String representation seems to always indicate the Favourite status of a Person as Favourited? 

https://github.com/AY2122S2-CS2103-W16-4/tp/blob/882af81d73d6e31c822d6bec61d72450977410b2/src/main/java/seedu/address/model/person/Person.java#L203-L205

**Comment by hsiaojietng** [comment]
Yup, seems like this is a bug. I will make the necessary changes.
