### ISSUE TITLE
Missing space between "1." & "Uploading an Image to an existing client" causing formatting error

### ISSUE THREAD

**Issue by waffledood** [AY2122S2-CS2103-W16-4/tp#200]
![image](https://user-images.githubusercontent.com/59903913/162627735-bbfb1a04-8d77-4e68-8f07-8cbbaff7c7ee.png)

as per image, it seems the intended format of "Viewing an Image" is to follow "Uploading an Image"? 

the formatting/indentation looks a bit off?

@howardwhw2 saw this, wanted to clarify with you

**Comment by howardwhw2** [comment]
It is a problem with the indentation thanks for alerting me about it. I will rectify it in my own PR
