### ISSUE TITLE
Tag name validation regex too restrictive

### ISSUE THREAD

**Issue by Ashuh** [AY2122S2-CS2103-W16-4/tp#3]
Currently, tag names must be alphanumeric, making tags such as "1 room" invalid.
The validation regex will have to modified to support additional characters.

Possible additional characters:
1. ` `
2. `$`

**Comment by waffledood** [comment]
As reference, the current regex is [`"\\p{Alnum}+"`](https://github.com/AY2122S2-CS2103-W16-4/tp/blob/1d184706b34044fb69dff780477ee67a54cd1b31/src/main/java/seedu/address/model/tag/Tag.java#L13)
