### ISSUE TITLE
Favourite feature not updating main window

### ISSUE THREAD

**Issue by Ashuh** [AY2122S2-CS2103-W16-4/tp#68]
@hsiaojietng I'm not sure if I'm doing something wrong but it seems that using the `favourite` command does not update the list displayed in the main window except for the first time it is used. 

The underlying data is updated correctly but I have to manually trigger the window to refresh by performing another command like `find` or `add`.

Steps to recreate bug:

1. Run `favourite 1`: Favourite status of Person 1 in the GUI will be updated
2. Run `favourite 1` again: Favourite status of Person 1 in the GUI remains unchanged
3. Use `add` command to add a person: GUI will display the newly added person and update the favourite status of Person 1

Can you verify if this happens for you too?

**Comment by hsiaojietng** [comment]
Yeap it happens for me as well but I just double click on the Person card for the status to refresh. Is this a bug?

**Comment by Ashuh** [comment]
I feel that this behaviour is kind of weird since other commands update the window instantly and a new user might not realize that they have to click the card for it to refresh. I think other teams would mostly likely consider this to be a bug.

**Comment by hsiaojietng** [comment]
Sure I will locate the problem and solve it
